packages/slate-types/src/nodes/ElementNode.ts

Fixes https://github.com/prezly/slate/issues/1

isElementNode does not enforce `children` property

---

packages/slate-editor/src/components/ImageWithLoadingPlaceholderV2.tsx

https://linear.app/prezly/issue/DEV-1074/the-editor-image-loader-shows-again-after-resizing-the-browser-window

[DEV-1074] The editor image loader shows again after resizing the browser window

---

packages/slate-editor/src/components/ImageSizeWarning/ImageSizeWarning.tsx
packages/slate-editor/src/components/ImageWithLoadingPlaceholderV2.tsx
packages/slate-editor/src/components/LoadingPlaceholderV2/Placeholder.tsx
packages/slate-editor/src/components/LoadingPlaceholderV2/index.ts
packages/slate-editor/src/components/TooltipV2/Tooltip.tsx
packages/slate-editor/src/components/TooltipV2/index.ts
packages/slate-editor/src/components/index.ts
packages/slate-editor/src/index.ts
packages/slate-editor/src/modules/editor-v4-components/FloatingContainer/Container.tsx
packages/slate-editor/src/modules/editor-v4-components/FloatingContainer/index.ts
packages/slate-editor/src/modules/editor-v4-components/LinkWithTooltip/LinkWithTooltip.tsx
packages/slate-editor/src/modules/editor-v4-components/index.ts
packages/slate-editor/src/modules/editor-v4-coverage/components/CoverageElement/CoverageElement.tsx
packages/slate-editor/src/modules/editor-v4-coverage/components/FloatingCoverageMenu/FloatingCoverageMenu.tsx
packages/slate-editor/src/modules/editor-v4-embed/components/FloatingEmbedInput/FloatingEmbedInput.tsx
packages/slate-editor/src/modules/editor-v4-floating-add-menu/FloatingAddMenu.tsx
packages/slate-editor/src/modules/editor-v4-loader/components/LoaderElement/LoaderElement.tsx
packages/slate-editor/src/modules/editor-v4-press-contacts/components/FloatingPressContactsMenu/FloatingPressContactsMenu.tsx
packages/slate-editor/src/modules/editor-v4-video/components/FloatingVideoInput/FloatingVideoInput.tsx
packages/slate-editor/src/modules/editor-v4-web-bookmark/components/FloatingWebBookmarkInput/FloatingWebBookmarkInput.tsx
packages/slate-editor/src/modules/editor-v4/index.ts

- Refactor component-as-namespace pattern to ES namespaced imports
They are better for IDEs, they are better for tree-shaking.

Refactor - Namespace exports

---

packages/slate-editor/src/components/Portals/TextSelectionPortalV2.tsx

- Add a check to disable popper positioning if selection is outside of the editor

[MT-4575] Fix text formatting toolbar being positioned outside of editable content

---

packages/slate-editor/src/modules/editor-v4/EditorV4.tsx

- new Video option replaces the old Embed Video
- new Web Bookmark option replaces Embed Link

[MT-4410][MT-4361] Make new blocks (Video & Bookmark) replace old ones

---

packages/slate-editor/src/components/Portals/BasePortalV2.scss
packages/slate-editor/src/components/Portals/BasePortalV2.tsx
packages/slate-editor/src/components/Portals/convertClientRect.ts
packages/slate-editor/src/modules/editor-v4-components/LinkMenu/LinkMenu.tsx
packages/slate-editor/src/modules/editor-v4-rich-formatting/components/RichFormattingMenu.tsx

Ticket: https://linear.app/prezly/issue/MT-4450/editor-creating-a-link-does-not-focus-url-input
with scroll:

[MT-4450] Creating a Link does not focus URL input

---

packages/slate-editor/src/modules/editor-v4-floating-add-menu/FloatingAddMenu.scss
packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/ModernDropdown.scss

[MT-4661] Scrolling in the dropdown does not work on Mac

---

packages/slate-editor/src/components/FancyScrollbars.tsx
packages/slate-editor/src/modules/editor-v4-floating-add-menu/FloatingAddMenu.tsx
packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/ModernDropdown.scss
packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/ModernDropdown.tsx
packages/slate-editor/src/modules/editor-v4-floating-add-menu/lib/sortBetaOptionsLast.ts

- Fix a glitch with wrong order when navigating over menu items with keyboard UP and DOWN keys
- Keep active [+] menu item within the scroll viewport during keyboard navigation

[MT-4672] Fix - [+] button menu keyboard navigation

---

packages/slate-editor/src/modules/editor-v4-html/HtmlExtension.tsx
packages/slate-editor/src/modules/editor-v4-html/components/HtmlElement.tsx
packages/slate-editor/src/modules/editor-v4-html/components/index.ts
packages/slate-editor/src/modules/editor-v4-html/constants.ts
packages/slate-editor/src/modules/editor-v4-html/index.ts
packages/slate-editor/src/modules/editor-v4-html/lib/createHtmlBlock.ts
packages/slate-editor/src/modules/editor-v4-html/lib/index.ts
packages/slate-editor/src/modules/editor-v4-html/lib/normalizeRedundantHtmlBlockAttributes.ts
packages/slate-editor/src/modules/editor-v4-html/lib/parseSerializedElement.ts
packages/slate-editor/src/modules/editor-v4-html/transforms/index.ts
packages/slate-editor/src/modules/editor-v4-html/transforms/removeHtmlBlock.ts
packages/slate-editor/src/modules/editor-v4/getEnabledExtensions.ts
packages/slate-types/src/nodes/HtmlNode.ts
packages/slate-types/src/nodes/index.ts

- Add `html` node type to the model
- Add a simple block renderer to the editor

[MT-4552] Feature - HTML blocks support

---

packages/slate-editor/src/modules/editor-v4-events/types.ts
packages/slate-editor/src/modules/editor-v4-loader/components/LoaderElement/LoaderElement.tsx
packages/slate-editor/src/modules/editor-v4-loader/types.ts
packages/slate-editor/src/modules/editor-v4-story-embed/StoryEmbedExtension.tsx
packages/slate-editor/src/modules/editor-v4-story-embed/components/FloatingStoryEmbedInput/FloatingStoryEmbedInput.scss
packages/slate-editor/src/modules/editor-v4-story-embed/components/FloatingStoryEmbedInput/FloatingStoryEmbedInput.tsx
packages/slate-editor/src/modules/editor-v4-story-embed/components/FloatingStoryEmbedInput/index.ts
packages/slate-editor/src/modules/editor-v4-story-embed/components/StoryEmbedElement/StoryEmbedElement.module.scss
packages/slate-editor/src/modules/editor-v4-story-embed/components/StoryEmbedElement/StoryEmbedElement.tsx
packages/slate-editor/src/modules/editor-v4-story-embed/components/StoryEmbedElement/index.ts
packages/slate-editor/src/modules/editor-v4-story-embed/components/index.ts
packages/slate-editor/src/modules/editor-v4-story-embed/constants.ts
packages/slate-editor/src/modules/editor-v4-story-embed/index.ts
packages/slate-editor/src/modules/editor-v4-story-embed/lib/createStoryEmbed.ts
packages/slate-editor/src/modules/editor-v4-story-embed/lib/index.ts
packages/slate-editor/src/modules/editor-v4-story-embed/lib/normalizeRedundantStoryEmbedAttributes.ts
packages/slate-editor/src/modules/editor-v4-story-embed/lib/parseSerializedElement.ts
packages/slate-editor/src/modules/editor-v4-story-embed/lib/useFloatingStoryEmbedInput.ts
packages/slate-editor/src/modules/editor-v4-story-embed/transforms/index.ts
packages/slate-editor/src/modules/editor-v4-story-embed/transforms/removeStoryEmbed.ts
packages/slate-editor/src/modules/editor-v4-story-embed/transforms/updateStoryEmbed.ts
packages/slate-editor/src/modules/editor-v4-story-embed/types.ts
packages/slate-editor/src/modules/editor-v4/EditorV4.tsx
packages/slate-editor/src/modules/editor-v4/getEnabledExtensions.ts
packages/slate-editor/src/modules/editor-v4/menuOptions.tsx
packages/slate-editor/src/modules/editor-v4/types/index.ts
packages/slate-types/src/nodes/StoryEmbedNode.ts
packages/slate-types/src/nodes/index.ts

Companion PR:
* https://github.com/prezly/prezly/pull/10722

[DEV-4541] Story Embed rich content block

---

packages/slate-editor/src/modules/editor-v4-video/components/VideoElement/VideoElement.scss
packages/slate-editor/src/modules/editor-v4-video/components/VideoElement/VideoElement.tsx

Origin from https://github.com/prezly/slate/commit/c3c9b243b2c249b7fde5934b1ff6a1496cae81f1

[MT-4876] Remove video overlay

---

packages/slate-editor/src/modules/editor-v4/EditorV4.tsx

From https://github.com/ianstormtaylor/slate/pull/4540#issuecomment-951380551

[DEV-5017] Assign value to editor children

---

package-lock.json
packages/slate-editor/src/modules/editor-v4/EditorV4.stories.tsx

https://linear.app/prezly/issue/MT-4877/add-the-editor-to-storybook

[MT4877] Added EditorV4 component to storybook

---

packages/slate-editor/src/modules/editor-v4-file-attachment/components/FileAttachment/Subtitle.tsx
packages/slate-editor/src/modules/editor-v4-file-attachment/components/FileAttachment/Title.tsx
packages/slate-editor/src/modules/editor-v4-file-attachment/components/FileAttachmentMenu.tsx

https://user-images.githubusercontent.com/41072665/163953746-cf31ba06-d152-4804-a84a-ddfa2996d446.mp4

[MT-4888] FIX: Unable to change title of attachments once they're added

---

packages/slate-editor/src/components/EditorBlock/ResizableEditorBlock.tsx
packages/slate-editor/src/components/EditorBlock/Size.ts
packages/slate-editor/src/modules/editor-v4-floating-add-menu/lib/isMenuHotkey.ts
packages/slate-editor/src/modules/editor-v4-image/components/ImageElement.tsx
packages/slate-editor/src/modules/editor-v4-image/lib/createImage.ts
packages/slate-editor/src/modules/editor-v4-image/lib/normalizeRedundantImageAttributes.ts
packages/slate-types/src/nodes/ImageNode.ts

- Update `ImageNode` to support new `align` property
- Update `ImageNode` to support absolute sizing options in pixels
- No UI changes yet

[MT-4872] Feature - New ImageNode model features

---

packages/slate-editor/src/components/EditorBlock/EditorBlock.module.scss
packages/slate-editor/src/components/EditorBlock/ResizableEditorBlock.tsx
packages/slate-editor/src/components/EditorBlock/ResizeButton.module.scss
packages/slate-editor/src/components/EditorBlock/ResizeButton.tsx
packages/slate-editor/src/components/EditorBlock/lib.ts

https://user-images.githubusercontent.com/370680/165946744-6f1c18c3-0c6a-439d-a7d1-f0d7f15fe621.mp4

[MT-4948] Implement left-positioned resize handler

---

packages/slate-editor/src/components/EditorBlock/EditorBlock.module.scss

Fix a regression introduced with #168

Fix `extendedHitArea` block variation

---

packages/slate-editor/src/extensions/galleries/components/Gallery/Gallery.module.scss
packages/slate-editor/src/extensions/galleries/components/Gallery/Gallery.tsx
packages/slate-editor/src/extensions/galleries/components/Gallery/GalleryTile.tsx
packages/slate-editor/src/extensions/galleries/components/Gallery/lib/calculateLayout.ts

There was a bug introduced in #188, causing full-width galleries to keep expanding horizontally forever

Fix - Gallery layout calculation

---

package-lock.json
package.json
packages/slate-editor/src/components/LoadingPlaceholder/ImageWithLoadingPlaceholder.tsx
packages/slate-editor/src/extensions/loader/components/LoaderElement.tsx
packages/slate-editor/src/lib/hooks/useAsyncProgressFn.ts
packages/slate-editor/src/modules/editor/lib/insertUploadingFile.ts

- Upgrade @prezly/progress-promise to v2
- Fix gallery versions for Safari 14 and below

[MT-5029] Fix - Gallery images are not visible in older Safari versions

---

packages/slate-commons/src/commands/alignment.ts
packages/slate-editor/src/extensions/tables/components/TableMenu.tsx
packages/slate-editor/src/extensions/tables/components/elements/TableCellElement.tsx
packages/slate-editor/src/extensions/tables/components/elements/TableRowElement.tsx
packages/slate-editor/src/extensions/tables/components/elements/elements.module.scss
packages/slate-editor/src/modules/rich-formatting-menu/RichFormattingMenu.tsx
packages/slate-editor/src/modules/rich-formatting-menu/components/Toolbar.tsx
packages/slate-editor/src/modules/rich-formatting-menu/types.ts
packages/slate-tables/src/TablesEditor.tsx
packages/slate-tables/src/core/Matrix/Matrix.ts
packages/slate-tables/src/core/Matrix/MatrixCell.ts
packages/slate-tables/src/core/Matrix/MatrixColumn.ts
packages/slate-tables/src/core/Matrix/MatrixRow.ts
packages/slate-tables/src/core/Traverse/Traverse.ts
packages/slate-tables/src/queries/index.ts
packages/slate-tables/src/queries/isHeaderCell.ts

Add cell content formatting

---

packages/slate-editor/src/components/FancyScrollbars.tsx
packages/slate-editor/src/extensions/floating-add-menu/FloatingAddMenu.tsx
packages/slate-editor/src/extensions/floating-add-menu/components/Dropdown.tsx
packages/slate-editor/src/extensions/floating-add-menu/lib/groupOptions.ts
packages/slate-editor/src/extensions/floating-add-menu/lib/index.ts
packages/slate-editor/src/extensions/floating-add-menu/lib/prependSuggestions.ts
packages/slate-editor/src/extensions/floating-add-menu/types.ts
packages/slate-editor/src/modules/editor/Editor.tsx
packages/slate-editor/src/modules/editor/menuOptions.tsx

[MT-5131] Feature - [+] menu "Suggestions" group

---

packages/slate-editor/src/components/TooltipV2/Tooltip.module.scss
packages/slate-editor/src/extensions/floating-add-menu/FloatingAddMenu.tsx
packages/slate-editor/src/extensions/floating-add-menu/index.ts
packages/slate-editor/src/extensions/floating-add-menu/types.ts
packages/slate-editor/src/modules/editor/Editor.stories.tsx
packages/slate-editor/src/modules/editor/types.ts

- Change [+] menu tooltip types to allow any content (not just a string)

[MT-5125] Change - Rich [+] menu tooltip content

---

packages/slate-commons/src/commands/index.ts
packages/slate-commons/src/commands/isCursorOnEdgeOfContainer.ts
packages/slate-tables/src/core/onKeyDown.ts

[MT-5197] Suggestion - Edge line detection improvements

---

packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx

[MT-5127] Focus editor on closing toolbar

---

packages/slate-editor/src/modules/nodes-hierarchy/fixers/convertToParagraph.ts

See https://github.com/prezly/slate/pull/266#discussion_r930036787

[MT-5209] Remove unused code

---

packages/slate-editor/src/extensions/floating-add-menu/components/Dropdown.module.scss
packages/slate-editor/src/extensions/floating-add-menu/components/Dropdown.tsx

[MT-5210] Feature - Update layout and functionality of plus menu dropdown

---

packages/slate-editor/src/modules/editor/menuOptions.tsx

[MT-5194] Update [+] menu Suggestions order

---

packages/slate-editor/src/extensions/floating-add-menu/components/Dropdown.tsx

See https://linear.app/prezly/issue/MT-5210/update-layout-and-functionality-of-[]-dropdown#comment-c710bc14

[MT-5210] Fix - [+] menu position on initial render

---

packages/slate-editor/src/extensions/floating-add-menu/components/Dropdown.module.scss
packages/slate-editor/src/extensions/floating-add-menu/components/Dropdown.tsx

https://linear.app/prezly/issue/MT-5210/update-layout-and-functionality-of-dropdown#comment-f06fa9ff

[MT-5210] Fix - [+] menu min-height when filtered

---

packages/slate-editor/src/extensions/tables/components/elements/elements.module.scss

[MT-5232] Change table layout to auto

---

.eslintrc.cjs
packages/slate-editor/src/components/LoadingPlaceholder/LoadingPlaceholder.stories.tsx
packages/slate-editor/src/extensions/tables/normalization.test.tsx
packages/slate-editor/src/modules/events/EventsEditor.ts
packages/slate-editor/src/modules/uploadcare/UploadcareEditor.ts
packages/slate-tables/src/normalization/insertMissingCells.ts

[MT-5032] Fix - Editor crashing on pasting Table from a web-page

---

packages/slate-editor/src/extensions/inline-links/components/LinkElement.tsx
packages/slate-editor/src/modules/rich-formatting-menu/RichFormattingMenu.tsx

[DEV-7410] Allow partial link selection

---

packages/slate-commons/src/commands/index.ts
packages/slate-commons/src/commands/resetSelection.ts
packages/slate-editor/src/modules/editor/Editor.tsx
packages/slate-editor/src/modules/editor/types.ts

[DEV-7357] Add clear selection

---

.gitignore
packages/slate-editor/src/modules/rich-formatting-menu/RichFormattingMenu.tsx

[QRF-103] Fix - Editor expands selection to whole paragraphs when trying to link specific portion of text

---

packages/slate-editor/src/extensions/placeholders/components/InputPlaceholder.tsx
packages/slate-editor/src/extensions/placeholders/components/InputPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/components/Placeholder.tsx
packages/slate-editor/src/extensions/placeholders/elements/EmbedPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/SocialPostPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/VideoPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/WebBookmarkPlaceholderElement.tsx

- Embed Placeholder
- Social Post Placeholder
- Video Placeholder
- Web Bookmark Placeholder

[DEV-8930] Fix - Allow protocol-less URLs in placeholders

---

packages/slate-editor/src/modules/editor/Editor.tsx

Related conversation https://github.com/prezly/slate/pull/300#discussion_r982446191

[DEV-8881] Use correct close callback for FloatingStoryEmbedInput

---

packages/slate-editor/src/components/Input/Input.module.scss
packages/slate-editor/src/extensions/placeholders/components/Frame.module.scss
packages/slate-editor/src/extensions/placeholders/components/Frame.tsx
packages/slate-editor/src/extensions/placeholders/components/InputPlaceholder.tsx
packages/slate-editor/src/extensions/placeholders/components/InputPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/components/Placeholder.tsx
packages/slate-editor/src/extensions/placeholders/components/PlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/components/SearchInputPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/AttachmentPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/ContactPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/EmbedPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/GalleryPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/ImagePlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/SocialPostPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/VideoPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/WebBookmarkPlaceholderElement.tsx

- Cursor when hovering Input field button
- Only blocks that has drag-n-drop functionality should have the dashed border. All other blocks should not have any border
- Remove subtitle from "Uploading" states
- Add missing red border to invalid input field state
- Deactivate active Input Placeholder when cursor has been moved away 
- Video should have same size as image/gallery (same proportions)

[DEV-8943] Feature - Smaller findings

---

packages/slate-editor/src/extensions/placeholders/components/LoadingDots.module.scss
packages/slate-editor/src/extensions/placeholders/components/LoadingDots.stories.tsx
packages/slate-editor/src/extensions/placeholders/components/LoadingDots.tsx
packages/slate-editor/src/extensions/placeholders/components/Placeholder.stories.tsx
packages/slate-editor/src/extensions/placeholders/elements/AttachmentPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/EmbedPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/GalleryPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/ImagePlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/SocialPostPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/VideoPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/WebBookmarkPlaceholderElement.tsx

- Implement pulsating dots for uploading states

[DEV-8919] Feature - Uploading states

---

packages/slate-editor/src/extensions/placeholders/elements/AttachmentPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/GalleryPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/ImagePlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/VideoPlaceholderElement.tsx

[QRF-341] Update placeholder texts

---

packages/slate-editor/src/components/EditorBlock/Menu.module.scss
packages/slate-editor/src/components/EditorBlock/Menu.tsx
packages/slate-editor/src/modules/popper-options-context/types.ts
packages/slate-editor/src/styles/variables.scss

Suggestion to make menu adaptive to the screen size

Suggestion - Auto menu placement

---

packages/slate-editor/src/components/EditorBlock/EditorBlock.module.scss
packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx
packages/slate-editor/src/components/EditorBlock/ResizableEditorBlock.tsx
packages/slate-editor/src/components/EditorBlock/ResizeButton.module.scss
packages/slate-editor/src/components/EditorBlock/ResizeButton.tsx

https://linear.app/prezly/issue/QRF-288/image-settings-menu-covering-resize-button

[QRF-288] Rework resize handles

---

package-lock.json
packages/slate-editor/package.json
packages/slate-types/package.json

See https://github.com/prezly/javascript-sdk/releases/tag/v10.0.0

Upgrade @prezly/sdk to the latest version v10

---

packages/slate-editor/src/modules/editor/lib/file-attachment/handleEditAttachment.ts

We handle filename normalization in uploadcare https://github.com/prezly/uploadcare/pull/7

[QRF-119] Remove file name forbidden characters replacement

---

package-lock.json
package.json
packages/slate-commons/package.json
packages/slate-editor/package.json
packages/slate-lists/package.json
packages/slate-tables/package.json
packages/slate-types/package.json

Update `slate` dependencies to the latest versions

---

packages/slate-editor/src/extensions/press-contacts/lib/createContactNode.ts
packages/slate-editor/src/modules/nodes-hierarchy/tests/Contact.test.tsx
packages/slate-editor/src/modules/nodes-hierarchy/tests/__snapshots__/Contact.test.tsx.snap
packages/slate-types/src/sdk/ContactInfo.ts

Alternative to https://github.com/prezly/slate/pull/378

[DEV-9878] Normalize ContactNode `website` before storing

---

package-lock.json
packages/slate-editor/package.json

https://linear.app/prezly/issue/QRF-915/cannot-paste-url

[QRF-915] Decrease slate version

---

packages/slate-editor/src/modules/editor/lib/file-attachment/handleEditAttachment.ts

Apply the same logic as we have on file upload when we edit the file

[QRF-914] Apply uploadcare transformations on edit

---

packages/slate-editor/src/modules/nodes-hierarchy/fixers/index.ts
packages/slate-editor/src/modules/nodes-hierarchy/fixers/removeNode.ts
packages/slate-editor/src/modules/nodes-hierarchy/hierarchySchema.ts
packages/slate-editor/src/modules/nodes-hierarchy/tests/AnyNode.test.tsx
packages/slate-editor/src/modules/nodes-hierarchy/tests/__snapshots__/AnyNode.test.tsx.snap
packages/slate-editor/src/modules/nodes-hierarchy/types.ts
packages/slate-editor/src/modules/nodes-hierarchy/withNodesHierarchy.ts

https://linear.app/prezly/issue/CARE-1320/client-gets-something-is-wrong-error

[CARE-1320] Handle case when node has no children

---

packages/slate-editor/src/extensions/web-bookmark/lib/createWebBookmark.ts

https://linear.app/prezly/issue/CARE-1306/web-bookmark-default-behaviour-open-in-new-tab

[CARE-1306] Web bookmark default behaviour - Open in new tab

---

packages/slate-editor/src/styles/variables.scss

A regression introduced by me in #411

[CARE-1603] Fix toolbar menu missing spacing

---

packages/slate-editor/src/components/Input/Input.module.scss
packages/slate-editor/src/components/Input/Input.tsx
packages/slate-editor/src/components/SearchInput/SearchInput.tsx
packages/slate-editor/src/extensions/placeholders/PlaceholdersExtension.tsx
packages/slate-editor/src/extensions/placeholders/components/SearchInputPlaceholder.tsx
packages/slate-editor/src/extensions/placeholders/components/SearchInputPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/ContactPlaceholderElement.tsx

This will allow us to render anything in front of the input.

[DEV-10754] Add support for input addon in ContactPlaceholderElement

---

packages/slate-editor/src/modules/rich-formatting-menu/RichFormattingMenu.tsx

[DEV-10901] Do not allow changing type or link title and subtitle headings

---

packages/slate-editor/src/modules/editor/Editor.tsx

To only blur if both `mousedown` and `mouseup` events happened outside of the editor.
Related to QRF-439 (#361)

[CARE-1904][CARE-1319] Fix `blurOnClickOutside` behavior

---

packages/slate-editor/src/extensions/floating-add-menu/components/Dropdown.module.scss
packages/slate-editor/src/extensions/floating-add-menu/components/Dropdown.tsx
packages/slate-editor/src/modules/editor/menuOptions.tsx

[CARE-1916] Remove `new` and `testing` labels from editor blocks

---

packages/slate-editor/src/extensions/placeholders/elements/ContactPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/CoveragePlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/EmbedPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/SocialPostPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/StoryBookmarkPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/StoryEmbedPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/VideoPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/WebBookmarkPlaceholderElement.tsx
packages/slate-editor/src/extensions/story-bookmark/components/StoryBookmarkElement/StoryBookmarkElement.tsx
packages/slate-editor/src/modules/editor/Editor.tsx
packages/slate-editor/src/modules/events/types.ts

- Drop unused and duplicated ones
- Rename ones that have been repurposed
- Change payload shapes to be consistent

[CARE-1797] Cleanup editor events

---

packages/slate-editor/src/extensions/button-block/ButtonBlockExtension.tsx

[DEV-11326] Increase spacing above and below button block in editor

---

packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx
packages/slate-editor/src/components/EditorBlock/getMenuPopperModifiers.ts
packages/slate-editor/src/extensions/button-block/components/ButtonBlockElement.tsx
packages/slate-editor/src/modules/popper-options-context/types.ts

https://github.com/prezly/slate/assets/43710420/be8d0ff7-3d71-453d-96f6-0548cb92e796

[DEV-11280] Position overlay menu below the button element

---

packages/slate-editor/src/extensions/button-block/components/Button/Button.module.scss

[DEV-11397] Fix long button text wrapping

---

packages/slate-editor/src/extensions/video/VideoExtension.tsx
packages/slate-editor/src/extensions/video/components/VideoElement.tsx
packages/slate-editor/src/extensions/video/components/VideoMenu.module.scss
packages/slate-editor/src/extensions/video/components/VideoMenu.tsx
packages/slate-editor/src/extensions/video/index.ts
packages/slate-editor/src/extensions/video/lib/createVideoBookmark.ts
packages/slate-editor/src/extensions/video/lib/normalizeRedundantVideoAttributes.ts
packages/slate-editor/src/extensions/video/lib/parseSerializedElement.ts
packages/slate-editor/src/extensions/video/transforms/index.ts
packages/slate-editor/src/extensions/video/transforms/removeVideo.ts
packages/slate-editor/src/extensions/video/transforms/updateVideo.ts
packages/slate-editor/src/extensions/video/types.ts
packages/slate-editor/src/modules/nodes-hierarchy/hierarchySchema.ts
packages/slate-editor/src/modules/nodes-hierarchy/queries/isAllowedOnTopLevel.ts
packages/slate-editor/src/modules/nodes-hierarchy/tests/Video.test.tsx
packages/slate-editor/src/modules/nodes-hierarchy/tests/__snapshots__/Video.test.tsx.snap
packages/slate-types/src/nodes/VideoNode.ts

[Screencast from 2023-08-17 16-11-24.webm](https://github.com/prezly/slate/assets/370680/22bcbf77-2ff1-4916-b309-768040b74885)

[DEV-7586] Feature - Implement UI for video block settings

---

packages/slate-editor/src/extensions/placeholders/PlaceholdersExtension.tsx
packages/slate-editor/src/extensions/placeholders/elements/EmbedPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/SocialPostPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/elements/VideoPlaceholderElement.tsx
packages/slate-editor/src/extensions/placeholders/lib/handleOembed.ts
packages/slate-editor/src/extensions/placeholders/lib/index.ts

Works in pair with: https://github.com/prezly/prezly/pull/13766

[DEV-7592] Feature - Reroute embeds to video or web bookmark, if it serves better

---

packages/slate-editor/src/modules/editor/menuOptions.tsx

As per https://linear.app/prezly/issue/DEV-11533/review-order-of-embeds

[DEV-11533] Reorder embed providers menu items

---

packages/slate-editor/src/extensions/inline-links/InlineLinksExtension.tsx
packages/slate-editor/src/extensions/inline-links/behaviour/index.ts
packages/slate-editor/src/extensions/inline-links/behaviour/withPastedContentAutolinking.ts
packages/slate-editor/src/extensions/inline-links/behaviour/withSelectionAutolinking.ts
packages/slate-editor/src/extensions/inline-links/lib/autolinkPlaintext.test.ts
packages/slate-editor/src/extensions/inline-links/lib/autolinkPlaintext.ts
packages/slate-editor/src/extensions/inline-links/lib/createLink.ts
packages/slate-editor/src/extensions/inline-links/lib/index.ts
packages/slate-editor/src/extensions/inline-links/lib/isUrl.ts
packages/slate-editor/src/lib/index.ts
packages/slate-editor/src/lib/urls.ts

[Screencast from 2023-09-06 16-12-55.webm](https://github.com/prezly/slate/assets/370680/c4bc8e03-9577-424f-a336-303b1c6f9941)

[DEV-11519] Feature - Autolink URLs in the pasted content

---

packages/slate-editor/src/extensions/placeholders/PlaceholdersExtension.tsx
packages/slate-editor/src/extensions/placeholders/behaviour/withPastedUrlsUnfurling.ts
packages/slate-editor/src/modules/editor/getEnabledExtensions.ts
packages/slate-editor/src/modules/rich-formatting-menu/RichFormattingMenu.tsx

[CARE-3627] Fix - Disable link unfurling inside tables

---

packages/slate-editor/src/extensions/galleries/components/Gallery/GalleryTile.tsx

[DEV-12579] Fix - Add tooltips to Crop and Delete buttons

---

packages/slate-editor/package.json
packages/slate-types/package.json

See https://github.com/prezly/javascript-sdk/releases/tag/v20.0.0

Upgrade @prezly/sdk package

---

packages/slate-editor/src/extensions/galleries/GalleriesExtension.tsx
packages/slate-editor/src/extensions/galleries/components/Gallery/Gallery.tsx
packages/slate-editor/src/extensions/galleries/components/Gallery/GalleryTile.tsx
packages/slate-editor/src/extensions/galleries/components/GalleryElement.tsx
packages/slate-editor/src/extensions/galleries/components/GalleryMenu.tsx
packages/slate-editor/src/modules/editor/getEnabledExtensions.ts
packages/slate-editor/src/modules/events/types.ts

Introduce necessary callbacks in order to allow tracking various gallery node interactions.

[CARE-4588] Feature - Introduce more callbacks in gallery extension

---

packages/slate-editor/src/extensions/callout/components/CalloutElement.module.scss
packages/slate-editor/src/modules/editor/Editor.module.scss

[DEV-13053] Fix - Remarks on the in editor callout block typography

---

packages/slate-editor/package.json
packages/slate-types/package.json

Required for https://github.com/prezly/prezly/pull/15585

[DEV-13699] Feature - Upgrade `@prezly/sdk` to latest version
