prezly/slate

.prettierignore
`dist` directories are not pushed to the repository. Nevertheless build fails because some of build fails are not prettified.
=> Update .prettierignore config to not verify builds

packages/slate-commons/src/commands/index.ts, packages/slate-commons/src/commands/normalizeNestedElement.ts, packages/slate-editor/src/modules/editor-v4-rich-formatting/lib/index.ts, packages/slate-editor/src/modules/editor-v4-rich-formatting/lib/normalizeNestedLink.ts, packages/slate-editor/src/modules/editor-v4/plugins/index.ts, packages/slate-editor/src/modules/editor-v4/plugins/withRootElements.ts
- Simplify `normalizeNestedElement()` normalizer interface
Also this change relaxing the expecrations on Element structure -- the check is delegated to the caller code, which is good.
=> Refactor - Simplify `normalizeNestedElement()` normalizer interface

packages/slate-editor/src/components/CloseButtonV2/CloseButtonV2.scss, packages/slate-editor/src/components/FloatingMenu/Dropdown.scss, packages/slate-editor/src/components/FloatingMenu/FloatingMenu.scss, packages/slate-editor/src/components/GalleryLayoutSettings/GalleryLayoutSettings.scss, packages/slate-editor/src/components/ImageSizeWarning/ImageSizeWarning.scss, packages/slate-editor/src/components/KeyboardKey/KeyboardKey.scss, packages/slate-editor/src/components/LoadingPlaceholderV2/LoadingPlaceholderV2.scss, packages/slate-editor/src/components/TooltipV2/TooltipV2.scss, packages/slate-editor/src/modules/editor-v4-components/FloatingContainer/components/Button/Button.scss, packages/slate-editor/src/modules/editor-v4-components/LinkMenu/LinkMenu.scss, packages/slate-editor/src/modules/editor-v4-coverage/components/CoverageElement/CoverageBlock/CoverageBlock.scss, packages/slate-editor/src/modules/editor-v4-coverage/components/CoverageElement/CoverageElement.scss, packages/slate-editor/src/modules/editor-v4-divider/components/DividerElement.scss, packages/slate-editor/src/modules/editor-v4-embed/components/EmbedElement/EmbedElement.scss, packages/slate-editor/src/modules/editor-v4-file-attachment/components/FileAttachmentElement/FileAttachmentElement.scss, packages/slate-editor/src/modules/editor-v4-galleries/components/GalleryElement/GalleryTooltip/GalleryTooltip.scss, packages/slate-editor/src/modules/editor-v4-image/components/ResizableContainer/ResizableContainer.scss, packages/slate-editor/src/modules/editor-v4-mentions/components/MentionElement/MentionElement.scss, packages/slate-editor/src/modules/editor-v4-press-contacts/components/JobDescription/JobDescription.scss, packages/slate-editor/src/modules/editor-v4-press-contacts/components/PressContactElement/PressContactElement.scss, packages/slate-editor/src/modules/editor-v4-rich-formatting/components/BlockQuoteElement/BlockQuoteElement.scss, packages/slate-editor/src/styles/colors.scss, packages/slate-editor/src/styles/legacy-colors.scss, packages/slate-editor/src/styles/variables.scss
Based on DEV-4114 
We need to make sure this repo is using color codes consistent with the main app. However, it doesn't make sense to work on it now, but better to postpone and address in scope of MT-4461.
- Add `legacy-` prefix to all existing color variables
- Introduce new color variables to be used instead 
- No changes to the stylesheets yet
=> [DEV-4114] Chore - Preparation for colors consistency refactoring

packages/slate-editor/src/modules/editor-v4/EditorV4.tsx
- Do not override old Video & Link options with new Video & Bookmark nodes in "+" menu
=> [MT-4509] Tweak - New Video & Bookmark nodes menu options

.gitignore, .npmrc, package-lock.json, packages/slate-commons/.npmrc, packages/slate-commons/src/commands/index.ts, packages/slate-commons/src/commands/moveCursorToNextBlock.ts, packages/slate-commons/src/commands/moveCursorToPreviousBlock.test.tsx, packages/slate-commons/src/commands/moveCursorToPreviousBlock.ts, packages/slate-editor/.npmrc, packages/slate-editor/package.json, packages/slate-editor/src/modules/editor-v4-void/VoidExtension.tsx, packages/slate-editor/src/modules/editor-v4-void/constants.ts, packages/slate-editor/src/modules/editor-v4-void/index.ts, packages/slate-editor/src/modules/editor-v4/getEnabledExtensions.ts, packages/slate-hyperscript/.npmrc, packages/slate-lists/.npmrc, packages/slate-types/.npmrc
Ticket: https://linear.app/prezly/issue/MT-4521/selecting-divider-node-with-mouse-and-then-pressing-enter-does-not
Demo:
There is an issue with image component, on Down it skips the image, but on up it focuses on the image label text
=> Add Void extension

packages/slate-editor/src/modules/editor-v4-image/components/ImageElement/ImageElement.scss
ticket: https://linear.app/prezly/issue/MT-4530/pressing-up-or-down-on-image-blocks-doesnt-work-correctly
Demo:
=> Fix - Image block selection with keyboard arrows

packages/slate-editor/src/modules/editor-v4-image/ImageExtension.tsx
Ticket: https://linear.app/prezly/issue/MT-4531/selecting-all-caption-in-image-block-and-pressing-backspace-removes
Demo:
=> Fix - Selecting all caption in Image block and pressing Backspace removes whole block

packages/slate-commons/src/plugins/withUserFriendlyDeleteBehavior/withUserFriendlyDeleteBehavior.test.tsx, packages/slate-commons/src/plugins/withUserFriendlyDeleteBehavior/withUserFriendlyDeleteBehavior.ts
Ticket: https://linear.app/prezly/issue/MT-4532/wrong-behaviour-when-you-do-backspace-on-a-paragraph
=> MT-4532: Wrong behaviour when you do Backspace on a paragraph

packages/slate-lists/package.json
The peer dependency for React is too restrictive
=> Widen the peer dependency for React

packages/slate-editor/src/components/EditorBlock/EditorBlock.module.scss, packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx, packages/slate-editor/src/modules/editor-v4-divider/components/DividerElement.tsx, packages/slate-editor/src/modules/editor-v4-web-bookmark/components/WebBookmarkElement/WebBookmarkElement.module.scss, packages/slate-editor/src/modules/editor-v4-web-bookmark/components/WebBookmarkElement/WebBookmarkElement.tsx, packages/slate-editor/src/styles/shared.scss, packages/slate-editor/src/styles/variables.scss
Based on #104 
- Fix selection of Divider and Bookmark blocks with keyboard UP/DOWN navigation
- Fix Bookmark block selection state to match the designs (no rounded borders; no gray border)
- Refactor `EditorBlock` to pass Slate internal children as `children`
=> [MT-4673] Fix - Pressing UP key doesnt focus some void elements

packages/slate-editor/src/components/Portals/BasePortalV2.tsx
Before:
After:
There is still issue with arrow position when the target is huge, it is placed in the middle, but according to the designs it should be always on the left, thoughts?
=> [MT-4866] Fix arrow position at the beginning of target

packages/slate-editor/src/components/Portals/TextSelectionPortalV2.tsx, packages/slate-editor/src/modules/editor-v4-rich-formatting-menu/RichFormattingMenu.tsx
https://github.com/prezly/slate/pull/126#issue-1162705401
> There is still issue with arrow position when the target is huge, it is placed in the middle, but according to the designs it should be always on the left, thoughts?
=> [MT-4866] Fix Link Menu arrow positionioning

packages/slate-editor/src/modules/editor-v4-image/components/ImageElement/ImageElement.tsx, packages/slate-editor/src/modules/editor-v4-image/components/ResizableContainer/ResizableContainer.tsx, packages/slate-editor/src/modules/editor-v4-image/jsx.ts, packages/slate-editor/src/modules/editor-v4-image/lib/createImage.ts, packages/slate-editor/src/modules/editor-v4-image/lib/normalizeRedundantImageAttributes.ts, packages/slate-editor/src/modules/editor-v4-image/lib/parseSerializedElement.ts, packages/slate-editor/src/modules/editor-v4-image/transforms/removeImage.test.tsx, packages/slate-editor/src/modules/editor-v4-image/withImages.test.tsx, packages/slate-editor/src/modules/editor-v4/json.ts, packages/slate-editor/src/modules/editor-v4/lib/images/createHandleEditImage.ts, packages/slate-types/src/nodes/ImageNode.ts
The attribute does not seem to be used at all. I've checked the database and there are only a few image nodes having `width_factor` set to anything else except `100%`. All used in a few fairly old stories dating to 2018.
=> Refactor - Deprecate ImageNode `width_factor` property

packages/slate-editor/src/modules/editor-v4-floating-add-menu/FloatingAddMenu.tsx
https://user-images.githubusercontent.com/41072665/165494467-56a0b84a-628f-46a0-b9f4-5f96fba3e999.mp4
=> [MT-4670] Fix - Placeholder should not be visible for white-space-only text blocks

packages/slate-editor/src/components/ElementPlaceholder/ElementPlaceholder.module.scss, packages/slate-editor/src/components/ElementPlaceholder/ElementPlaceholder.tsx, packages/slate-editor/src/components/ElementPlaceholder/index.ts, packages/slate-editor/src/components/index.ts, packages/slate-editor/src/modules/editor-v4-coverage/components/CoverageElement/CoverageElement.tsx, packages/slate-editor/src/modules/editor-v4-coverage/lib/removeCoverage.ts, packages/slate-editor/src/modules/editor-v4-story-bookmark/components/StoryBookmarkElement/StoryBookmarkElement.tsx, packages/slate-editor/src/modules/editor-v4-story-bookmark/transforms/index.ts, packages/slate-editor/src/modules/editor-v4-story-bookmark/transforms/updateStoryBookmark.ts
As discussed in #168 
- Implement a nice placeholder for coverage fetching errors from #161 
- Implement click-on-placeholder functionality
- Improve a11y for ElementPlaceholder actions
=> Feature - Coverage block nice placeholder for error state

packages/slate-editor/src/modules/editor-v4-coverage/lib/createCoverage.ts, packages/slate-editor/src/modules/editor-v4-coverage/lib/normalizeRedundantCoverageAttributes.ts, packages/slate-editor/src/modules/editor-v4-coverage/lib/parseSerializedElement.ts, packages/slate-types/src/nodes/CoverageNode.ts
As mentioned in https://github.com/prezly/prezly/pull/10959#issuecomment-1125776566, 
there was a bug that lead to email editor content being constantly marked as modified.
I've narrowed it down to the mismatch between CoverageNode backend and frontend models:
- `new_tab`, `layout`, `show_thumbnail` attributes were sent from backend
- then frontend was automatically removing unknown attributes during the normalization process
- this made the in-editor content differ from the backend model, and marked the content as modified, triggering autosave
- ... repeating forever
=> Fix CoverageNode model mismatch between frontend and backend

packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx, packages/slate-editor/src/components/EditorBlock/Menu.tsx
- Allow editor block menu to leave the editor frame
Before:
After:
=> [MT-4960] Fix - Menu positioning

packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx, packages/slate-editor/src/components/EditorBlock/Overlay.tsx
Improve Image menu behavior vs caption-text selection
- Do not open the menu every time image caption text is focused
- Automatically close the menu when caption text is clicked
=> [MT-4965] Fix - Image menu overlapping with caption

packages/slate-commons/src/plugins/withInlineVoid.ts, packages/slate-commons/src/plugins/withNormalization.ts, packages/slate-commons/src/types/Extension.ts, packages/slate-editor/src/extensions/coverage/CoverageExtension.tsx, packages/slate-editor/src/extensions/divider/DividerExtension.tsx, packages/slate-editor/src/extensions/embed/EmbedExtension.tsx, packages/slate-editor/src/extensions/file-attachment/FileAttachmentExtension.tsx, packages/slate-editor/src/extensions/galleries/GalleriesExtension.tsx, packages/slate-editor/src/extensions/html/HtmlExtension.tsx, packages/slate-editor/src/extensions/image/ImageExtension.tsx, packages/slate-editor/src/extensions/inline-links/InlineLinksExtension.tsx, packages/slate-editor/src/extensions/loader/LoaderExtension.tsx, packages/slate-editor/src/extensions/mentions/MentionsExtension.ts, packages/slate-editor/src/extensions/mentions/test-utils.tsx, packages/slate-editor/src/extensions/paragraphs/ParagraphsExtension.tsx, packages/slate-editor/src/extensions/placeholder-mentions/PlaceholderMentionsExtension.tsx, packages/slate-editor/src/extensions/press-contacts/PressContactsExtension.tsx, packages/slate-editor/src/extensions/rich-formatting/RichFormattingExtension.tsx, packages/slate-editor/src/extensions/story-bookmark/StoryBookmarkExtension.tsx, packages/slate-editor/src/extensions/story-embed/StoryEmbedExtension.tsx, packages/slate-editor/src/extensions/user-mentions/UserMentionsExtension.tsx, packages/slate-editor/src/extensions/video/VideoExtension.tsx, packages/slate-editor/src/extensions/web-bookmark/WebBookmarkExtension.tsx
- Replace `inlineTypes` and `voidTypes` array (`string[]`) properties with more abstract `isInline` and `isVoid` checker functions.
This is one more step toward not depending on the `type` property being always present on node objects.
- Rename `normalizers` to `normalizeNode` to match [Slate API](https://docs.slatejs.org/concepts/11-normalizing#adding-constraints)
=> Refactor - Extensions inline/void checks

packages/slate-editor/src/components/EditorBlock/EditorBlock.module.scss, packages/slate-editor/src/extensions/image/components/ImageElement.module.scss, packages/slate-editor/src/extensions/image/components/ImageElement.tsx, packages/slate-editor/src/extensions/paragraphs/components/ParagraphElement.module.scss, packages/slate-editor/src/extensions/rich-formatting/components/Headings/HeadingElement.module.scss, packages/slate-editor/src/extensions/rich-formatting/components/Lists/ListElement.module.scss, packages/slate-editor/src/modules/editor/Editor.module.scss, packages/slate-editor/src/styles/variables.scss
- Rework spacing between blocks
Elements themselves are no longer responsible for outer spacing.
It's now set up centralized in the `Editable` element stylesheet (according to the Editor design specs)
- Improve image caption UX: it now has caption prompt visible, when the image block is selected
=> [MT-5004] Fix - Inter-blocks spacing

packages/slate-editor/src/components/LoadingPlaceholder/ImageWithLoadingPlaceholder.tsx, packages/slate-editor/src/lib/createImageProgressPromise/index.ts, packages/slate-editor/src/lib/fetchImageWithProgress/fetchImageWithProgress.ts, packages/slate-editor/src/lib/fetchImageWithProgress/fetchImageWithReadableStream.ts, packages/slate-editor/src/lib/fetchImageWithProgress/fetchImageWithXmlHttpRequest.ts, packages/slate-editor/src/lib/fetchImageWithProgress/index.ts, packages/slate-editor/src/lib/hooks/useImage.ts, packages/slate-editor/src/lib/index.ts
See comments in MT-5017 for details.
- Change `useImage` return object to provide `loaded` flag, instead of the blob URL
- Rename `useImage` internal functions for clarity
=> [MT-5017] Fix - Use image original src as a return value from the `useImage` hook

packages/slate-editor/src/extensions/list/components/ListElement.tsx, packages/slate-editor/src/extensions/list/components/ListItemElement.tsx, packages/slate-editor/src/extensions/list/components/ListItemTextElement.tsx
Bring back `ref` support to ListExtension elements
Refs are required by Slate in order to locate document nodes by their DOM elements. Without refs, it's likely to generate `Cannot resolve a DOM point from Slate point: {...}` errors when clicking on list nodes.
This is a regression introduced in #206
=> Fix - List elements `ref` support

packages/slate-editor/src/extensions/tables/components/TableMenu.tsx, packages/slate-editor/src/extensions/tables/normalization.test.tsx, packages/slate-editor/src/extensions/tables/normalization.ts
- Remove "border" toggle from the table menu
- Implement normalization to always add `border: true` on all TableNodes 
Extracted this part from #231, as it is a standalone change by itself
=> Change - Remove border toggle from Table menu 

packages/slate-editor/src/components/EditorBlock/EditorBlock.module.scss, packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx, packages/slate-editor/src/extensions/story-embed/components/StoryEmbedElement/StoryEmbedElement.tsx, packages/slate-editor/src/extensions/story-embed/lib/createStoryEmbed.ts
- Make `center` / `full` default StoryEmbed settings (see MT-5090)
- Fix visual presentation of StoryEmbed nodes in the editor
=> [MT-5090][MT-5071] Fix - StoryEmbed element

packages/slate-editor/src/extensions/insert-block-hotkey/InsertBlockHotkeyExtension.ts, packages/slate-editor/src/extensions/insert-block-hotkey/index.ts, packages/slate-editor/src/extensions/insert-block-hotkey/lib.ts, packages/slate-editor/src/modules/editor/getEnabledExtensions.ts
- Implement `InsertBlockHotkeyExtension` extension to support hotkeys to insert blocks above/below current top-level block
=> [MT-5184] Feature - Insert blocks above/below current block

packages/slate-editor/src/extensions/floating-add-menu/FloatingAddMenu.tsx, packages/slate-editor/src/extensions/floating-add-menu/FloatingAddMenuExtension.tsx, packages/slate-editor/src/extensions/floating-add-menu/lib/useMenuToggle.ts, packages/slate-editor/src/modules/editor/Editor.tsx, packages/slate-editor/src/modules/editor/getEnabledExtensions.ts, packages/slate-editor/src/modules/events/types.ts
Trigger editor events for the following actions (so we can bind analytics tracking to them):
- `[+] menu opened`
- `[+] menu closed`
- `[+] menu filtered`
- `[+] menu option clicked`
=> [MT-5132] Feature - Allow tracking of [+] menu options clicks

packages/slate-commons/src/commands/findLeafLocation.ts, packages/slate-commons/src/commands/findLeafPath.ts, packages/slate-commons/src/commands/findLeafPoint.ts, packages/slate-commons/src/commands/findLeafRange.ts, packages/slate-editor/src/extensions/paste-slate-content/PasteSlateContentExtension.ts, packages/slate-editor/src/extensions/paste-slate-content/lib/isFragment.ts, packages/slate-editor/src/extensions/tables/TablesExtension.tsx, packages/slate-editor/src/extensions/tables/onKeyDown.ts, packages/slate-editor/src/jsx.ts, packages/slate-editor/src/modules/editor/getEnabledExtensions.ts, packages/slate-tables/src/TablesEditor.ts, packages/slate-tables/src/core/onKeyDown.ts, packages/slate-tables/src/core/withTablesCopyPasteBehavior.ts, packages/slate-tables/src/queries/findParentCell.ts, packages/slate-tables/src/queries/findParentTable.ts, packages/slate-tables/src/queries/index.ts
- Re-enable forgotten extension of `PasteSlateContent` (see #210) (improves pasting for tables)
- Changes to copy/cut/paste behaviour:
- ~Copy the full table if multiple cells are selected~ (see [the discussion](https://github.com/prezly/slate/pull/257#discussion_r927127028))
- Copy/cut the full table if selection is collapsed and the cursor is inside table cell
- Unbind `TablesExtension` from `ParagraphsExtension` -- it's no longer dependent on it directly
=> [MT-5180] Fix - UX for copying/cutting/pasting tables

packages/slate-editor/src/extensions/floating-add-menu/lib/useKeyboardFiltering.ts
Putting the "beginning of word" matches first.
Filtering for `vid` will now put `Video` before `Divider`.
=> [MT-5203] Make the filtered results appear in a relevant order

packages/slate-commons/src/selection/highest.test.ts, packages/slate-commons/src/selection/highest.ts, packages/slate-editor/src/extensions/loader/transforms/replaceLoader.ts
The problem was here:
https://github.com/prezly/slate/blob/550124c7101cf67446cbad2559b799a86428bc7c/packages/slate-editor/src/modules/editor/lib/images/createImageEditHandler.ts#L41-L44
It should have been inserting a new paragraph at the top-most `Path` location, but `Selection.highest()` returned a `Range` for `editor.selection`. So it was inserting a paragraph inside another block.
This glitch was compensated by the previous normalization implementation. But not anymore, after we've refactored the normalization logic.
=> [MT-5219] Fix - Editor inserting empty block before cropped image

packages/slate-editor/src/extensions/press-contacts/components/FloatingPressContactsMenu.tsx, packages/slate-editor/src/extensions/press-contacts/components/PressContactElement.tsx, packages/slate-editor/src/extensions/press-contacts/types.ts, packages/slate-editor/src/index.ts, packages/slate-editor/src/modules/editor/Editor.tsx, packages/slate-editor/src/modules/editor/test-utils.ts, packages/slate-editor/src/modules/editor/types.ts
- Provide an additional imperative API method: `insertNodes()`
- Tweak ContactNode card rendering: do not render description block if it's empty
- Drop `newsroomSettingsUrl` prop from all components
- Additionally pass `onClose` to `renderSearch`
=> [DEV-8696] Feature - Editor Imperative API to insert nodes programmatically

packages/slate-editor/src/modules/editor/Editor.tsx, packages/slate-editor/src/modules/editor/types.ts
- Introduce one more imperative method: `updateNodes()`
Which is a proxy to `Transforms.setNodes()`
=> [DEV-8694] Feature - Editor imperative API to update nodes

packages/slate-commons/tsconfig.build.json, packages/slate-commons/tsconfig.json, packages/slate-editor/src/lib/hooks/react-use.ts, packages/slate-editor/tsconfig.build.json, packages/slate-editor/tsconfig.json, packages/slate-tables/tsconfig.build.json, packages/slate-tables/tsconfig.json, tsconfig.json
I had this recurring problem, where after clicking on a Typescript interface from a sibling package, my IDE was opening the target file from `node_modules`, not from a sibling `packages` folder.
These configuration changes fix that.
=> Dev - Fix "Go to definition" functionality

packages/slate-editor/src/extensions/placeholder-mentions/PlaceholderMentionsExtension.tsx, packages/slate-editor/src/extensions/placeholder-mentions/jsx.ts, packages/slate-editor/src/extensions/placeholder-mentions/lib/convertVariableNodesToPlaceholders.ts, packages/slate-editor/src/extensions/placeholder-mentions/lib/index.ts, packages/slate-editor/src/extensions/placeholder-mentions/normalization.test.tsx
A pre-deployment patch to properly roll out #298 
Just making sure the editor won't crash if it opens a document with `variable` type used in a Node.
With this change, `variable` node type will be automatically converted back to `placeholder`. Not ideal, but better than crashing the editor.
=> [DEV-8850] Minimal forward-compatibility with `variable` node types

packages/slate-editor/src/extensions/placeholders/elements/AttachmentPlaceholderElement.tsx, packages/slate-editor/src/extensions/placeholders/elements/GalleryPlaceholderElement.tsx, packages/slate-editor/src/extensions/placeholders/elements/ImagePlaceholderElement.tsx
Previously, the file drop events have been handled on multiple levels -- in the Placeholders and on the Editor level.
Resulting in Image being pasted twice.
=> [DEV-8914] Fix - File dropping in Chrome

packages/slate-editor/src/index.ts
Export `createPlaceholder` function so we can create an empty editor value with placeholder prefilled, [see example here](https://github.com/prezly/prezly/blob/023cb4a08f6403900eb3f7c44b62d364926d3b56/apps/backend/resources/javascripts/modules/editors/lib/createEditorValueWithGalleryPlaceholderAsString.ts).
=> Export createPlaceholder function

packages/slate-editor/src/extensions/loader/transforms/replaceLoader.ts, packages/slate-editor/src/modules/editor/lib/file-attachment/handleAddAttachment.ts, packages/slate-editor/src/modules/editor/lib/galleries/createHandleAddGallery.ts, packages/slate-editor/src/modules/editor/lib/galleries/createHandleEditGallery.ts, packages/slate-editor/src/modules/editor/lib/images/createImageAddHandler.ts, packages/slate-editor/src/modules/editor/lib/images/createImageEditHandler.ts, packages/slate-editor/src/modules/editor/lib/images/createImageReplaceHandler.ts, packages/slate-editor/src/modules/editor/lib/insertUploadingFile.ts, packages/slate-editor/src/modules/editor/plugins/withFilePasting.ts
When editing an image or a gallery, the original element is removed first, replaced by an empty paragraph, then replaced by the loader element and then replaced by the actual element.
This makes it fairly difficult to use the new `AllowedBlocks` extension because when you edit a gallery/image, for a brief moment the original element will be replaced by a paragraph. If you don't allow paragraphs, it will replace it with a custom block, which is not the desired outcome.
With these changes, when editing, the element is not removed and there's no paragraph used as an intermediary medium. Instead the element is replaced by a loader which is then replaced by the actual updated element.
There's a new `mode` option that affects whether to use replace or simply insert nodes as in some cases (e.g. …
=> Fix - Improve behaviour of image/gallery blocks

packages/slate-editor/src/modules/editor/types.ts
Looks like video prop is not used anymore
https://linear.app/prezly/issue/QRF-349/story-editor-embed-option-not-working
=> [QRF-349] Remove unused embed props

packages/slate-commons/src/commands/blur.ts, packages/slate-commons/src/commands/index.ts, packages/slate-editor/src/modules/editor/Editor.tsx, packages/slate-editor/src/modules/editor/types.ts
We want to be able to unfocus (blur) the editor in some cases.
=> Feature - Add blur method to the Editor component

packages/slate-editor/src/extensions/autoformat/withAutoformat.ts
https://linear.app/prezly/issue/QRF-151/editor-fails-using-in-unordered-lists
=> [QRF-151] Allow block auto-format only in paragraphs

packages/slate-editor/src/components/EditorBlock/ResizableEditorBlock.tsx
Followup on #342 
I've noticed that with the current implementation the resizing felt unnatural.
The reason is that by moving mouse by e.g. 10px, the image _width_ is reduced by 10px, but the dragged handle only shifts by 5px, which creates a dissonance between what user does and what happens on the screen.
Modifying the width by doubling the delta helps.
=> [QRF-288] Tweak Image resize handles behavior to feel more natural

packages/slate-editor/src/extensions/floating-add-menu/FloatingAddMenuExtension.tsx, packages/slate-editor/src/extensions/floating-add-menu/lib/index.ts, packages/slate-editor/src/extensions/floating-add-menu/lib/isMenuHotkey.ts, packages/slate-editor/src/extensions/floating-add-menu/lib/shouldShowMenuButton.ts, packages/slate-editor/src/extensions/floating-add-menu/lib/useKeyboardFiltering.ts
Some non-English keyboard layouts have to use Shift with a different key to produce the `/` trigger character. The code checking this event was too strict and did not allow the Shift key.
=> [DEV-6123] Allow optional Shift when detecting trigger character in FloatingAddMenu

packages/slate-editor/src/modules/components/BookmarkCard/BookmarkCard.module.scss
https://linear.app/prezly/issue/QRF-45/story-cards-cutting-off-title
Before:
After:
=> [QRF-45] Fix horizontal story bookmark provider width

packages/slate-editor/src/modules/editor/lib/file-attachment/handleEditAttachment.ts
https://linear.app/prezly/issue/QRF-119/unable-to-load-attached-pdf-in-campaign-email
=> [QRF-119] Forbid '/' in file names

packages/slate-editor/src/modules/editor/Editor.tsx, packages/slate-editor/src/modules/editor/types.ts
A side-effect of this change was that closing the menu via the X button also loses focus to the block.
In [QRF-441](https://linear.app/prezly/issue/QRF-441/media-galleries-edit-aside-component-focus-behaviour-is-wrong) we agreed that X button can stay with the current behavior.
Here's what it looks like in this PR:
https://user-images.githubusercontent.com/1641218/207571909-f846f8ad-a597-4e7c-bcbb-f6fa2c6a20c8.mov
=> [QRF-439] Add option to lose focus when clicking outside of the editor

packages/slate-editor/src/modules/editor/Editor.tsx, packages/slate-editor/src/modules/editor/types.ts
This is a follow-up for #361. It turned out that while clicking anywhere outside of the story composer worked perfectly, clicking on any textbox element (e.g. Title and Subtitle textareas) would result in those elements losing focus as well. With this workaround, and additional logic on the app side, everything now works as intended. I've added extra info in the typedoc to warn about the new behavior.
=> Ignore `blurOnOutsideClick` events on textbox elements

packages/slate-editor/src/extensions/placeholders/PlaceholdersExtension.tsx, packages/slate-editor/src/modules/editor/Editor.tsx, packages/slate-editor/src/modules/editor/getEnabledExtensions.ts, packages/slate-editor/src/modules/editor/test-utils.ts, packages/slate-editor/src/modules/editor/types.ts
Individual placeholders configuration is now part of individual `withXxx` extension configuration prop. For example, Coverage placeholder params are now passed with `withCoverage` extension configuration property.
=> [DEV-8970] Make PlaceholdersExtension auto-enable depending on enabled extensions

packages/slate-editor/src/extensions/placeholders/elements/InlineContactPlaceholderElement/InlineContactPlaceholderElement.tsx, packages/slate-types/src/nodes/ContactNode.ts
This is because a node property cannot be null.
See https://github.com/ianstormtaylor/slate/issues/4836
=> [DEV-9876] Change `ContactNode` model to `reference?: uuid`

packages/slate-editor/src/extensions/coverage/CoverageExtension.tsx, packages/slate-editor/src/extensions/embed/EmbedExtension.tsx, packages/slate-editor/src/extensions/file-attachment/FileAttachmentExtension.tsx, packages/slate-editor/src/extensions/galleries/GalleriesExtension.tsx, packages/slate-editor/src/extensions/image/ImageExtension.tsx, packages/slate-editor/src/extensions/inline-contacts/InlineContactsExtension.tsx, packages/slate-editor/src/extensions/press-contacts/PressContactsExtension.tsx, packages/slate-editor/src/extensions/story-bookmark/StoryBookmarkExtension.tsx, packages/slate-editor/src/extensions/story-embed/StoryEmbedExtension.tsx, packages/slate-editor/src/extensions/video/VideoExtension.tsx, packages/slate-editor/src/extensions/web-bookmark/WebBookmarkExtension.tsx, packages/slate-types/src/nodes/StoryBookmarkNode.ts
Related to #375 
- `AttachmentNode`
- `BookmarkNode`
- `CoverageNode`
- `EmbedNode`
- `ImageNode`
- `GalleryNode`
- `StoryBookmarkNode`
- `StoryEmbedNode`
- `VideoNode`
=> [DEV-9877] Implement smart content-aware comparisons for other block types

packages/slate-editor/src/components/EditorBlock/Menu.tsx
This virtual reference element was previously used to allow the menu flipping to the left if your browser has smaller width.
However with the rework of Story Composer page and the sidebar moving to the right of the page, there's not enough space on the left so flipping does not help there (it's currently broken anyway).
Removing the virtual reference element restores the proper menu positioning.
=> [DEV-9898] Get rid of virtual reference element in Menu component

packages/slate-editor/src/modules/editor/Editor.tsx
Another follow up for #361.
This one fixes the issue with Placeholder blocks not working with `blurOnOutsideClick` active, as well as resolving issue with FloatingAddMenu unwanted disappearing in some cases.
=> [CARE-439] Fix Placeholders not working with `blurOnOutsideClick`

packages/slate-editor/src/extensions/web-bookmark/WebBookmarkExtension.tsx, packages/slate-editor/src/extensions/web-bookmark/lib/index.ts, packages/slate-editor/src/extensions/web-bookmark/lib/normalizations.ts, packages/slate-types/src/lib/index.ts, packages/slate-types/src/lib/normalizeUrl.ts, packages/slate-types/src/sdk/ContactInfo.ts
As suggested by Lukas, I've ported the ContactNode normalization logic to `web-bookmarks` extension.
Due to issues with linking packages on the main app repo, I couldn't test it properly. I'll see if I can find a way to test it some other way.
=> [CARE-785] Fix `TypeError: Invalid URL` errors in Web Bookmarks

packages/slate-editor/src/modules/editor/Editor.tsx
The issue with the Link button on the text toolbar was pretty much the same as with Placeholders - the original clicked element is removed from the DOM, so it fails all of the `element.contains` checks.
I updated the check to not be Placeholder-specific and check that the element is still in the DOM at the time the handler catches the event.
=> [CARE-1064] Fix text toolbar issues with `blurOnOutsideClick`

package-lock.json, package.json, packages/slate-commons/package.json, packages/slate-commons/src/commands/getPrevChars.ts, packages/slate-commons/src/commands/index.ts, packages/slate-commons/src/commands/insertNodes.ts, packages/slate-commons/src/commands/isBlock.ts, packages/slate-commons/src/commands/isInline.ts, packages/slate-commons/src/commands/isSelectionAtBlockEnd.ts, packages/slate-commons/src/commands/isSelectionAtBlockStart.ts, packages/slate-commons/src/commands/isVoid.ts, packages/slate-commons/src/plugins/withBreaksOnExpandedSelection/withBreaksOnExpandedSelection.ts, packages/slate-commons/src/plugins/withBreaksOnVoidNodes/withBreaksOnVoidNodes.ts, packages/slate-editor/package.json, packages/slate-editor/src/components/SearchInput/SearchInput.tsx, packages/slate-editor/src/extensions/autoformat/transforms/autoformatBlock.ts, packages/slate-editor/src/extensions/paste-slate-content/lib/withSlatePasting.ts, packages/slate-editor/src/extensions/void/VoidExtension.tsx, packages/slate-editor/src/modules/editor/lib/createOnCut.ts, packages/slate-editor/src/modules/editor/lib/useCursorInView.ts, packages/slate-lists/package.json, packages/slate-tables/package.json, packages/slate-types/package.json
Fixes #367
I've introduced helper functions for `isBlock`, `isInline` and `isVoid` so we don't have to call `Editor.isElement` with every usage since the types [have been fixed now](https://github.com/ianstormtaylor/slate/pull/5254).
=> [CARE-1091] Upgrade Slate packages

packages/slate-editor/src/extensions/snippet/lib/useFloatingSnippetInput.ts
https://linear.app/prezly/issue/CARE-1293/snippet-doesnt-match-when-pasted-in-a-campaignstory
=> [CARE-1293] Snippet doesn't match when pasted

packages/slate-editor/src/modules/nodes-hierarchy/hierarchySchema.ts, packages/slate-editor/src/modules/nodes-hierarchy/normilizers/allowChildren.test.tsx, packages/slate-editor/src/modules/nodes-hierarchy/normilizers/allowChildren.ts, packages/slate-editor/src/modules/nodes-hierarchy/normilizers/disallowMark.ts, packages/slate-editor/src/modules/nodes-hierarchy/normilizers/mustHaveChildren.ts, packages/slate-editor/src/modules/nodes-hierarchy/normilizers/removeWhenNoChildren.ts, packages/slate-editor/src/modules/nodes-hierarchy/tests/AnyNode.test.tsx, packages/slate-editor/src/modules/nodes-hierarchy/types.ts, packages/slate-editor/src/modules/nodes-hierarchy/withNodesHierarchy.ts
- Revert fix for CARE-1320 (see #404)
The problem with this fix was that it's calling normalization _on absolutely every node_ in the document tree _on every keystroke_, which is A LOT for large documents. This was causing a major hit on the editor performance.
- Minor optimization on avoiding calling `Node.get()` in every normalizer
=> [CARE-1379] Quickfix - Prezly editor is very slow

.github/workflows/build.yml, .github/workflows/dependencies.yml, .github/workflows/prettier.yml, .github/workflows/storybook.yml, .github/workflows/test.yml, package.json, packages/slate-editor/storybook/.npmrc
- Simplify Github Actions configuration by extracting common steps into a composite action
See https://github.com/prezly/setup-github-actions
- Open "Create Release" page after publishing
- Improve `storybook` sub-package caching
=> Dev - Simplify & Improve GitHub actions

packages/slate-editor/package.json, packages/slate-editor/src/components/Menu/Dropdown.module.scss, packages/slate-editor/src/components/Menu/Dropdown.tsx, packages/slate-editor/src/components/Menu/Menu.module.scss, packages/slate-editor/src/components/Menu/Menu.stories.tsx, packages/slate-editor/src/styles/helpers.scss
There are two other places that need to be replaced:
- [MentionsDropdown](https://github.com/prezly/slate/blob/950cd7787fae1ec1a36ad3eb461ff8dbf5c0ef79/packages/slate-editor/src/extensions/mentions/components/MentionsDropdown.tsx#LL6C3-L6C3)
- [Dropdown (floating-add-menu)](https://github.com/prezly/slate/blob/950cd7787fae1ec1a36ad3eb461ff8dbf5c0ef79/packages/slate-editor/src/extensions/floating-add-menu/components/Dropdown.tsx#LL6C3-L6C3)
Will replace them in their corresponding PRs.
---
It now supports a focus trap as well as keyboard navigation:
https://github.com/prezly/slate/assets/67554982/df1f0383-ffcb-4358-a348-68862b387ce3
=> [CARE-1580] Refactor - Replace react-bootstrap's `Dropdown` with headlessui's `Listbox` in `Menu.Dropdown`

packages/slate-editor/src/components/SearchInput/SearchInput.tsx, packages/slate-editor/src/extensions/placeholders/elements/ContactPlaceholderElement.tsx, packages/slate-editor/src/modules/editor/menuOptions.tsx, packages/slate-editor/src/modules/events/EventsEditor.ts, packages/slate-editor/src/modules/events/types.ts
Added an event listener that allows us to trigger the search from outside of the editor, example usage [can be found here](https://github.com/prezly/prezly/pull/13210/files#diff-ecc8a3a52125ed26cf02f50a1cc681c82d79ab001c491a275262e6ebec91db06R36-R38).
=> [DEV-10754] Allow triggering search via events, minor text changes

packages/slate-editor/src/extensions/press-contacts/PressContactsExtension.tsx
This is a follow up to #418.
I've noticed changing the options in the contact's menu did not trigger a value change and then realised I forgot to update the equality checking function.
=> Fix - Compare options first before comparing references in contacts

packages/slate-editor/src/extensions/floating-add-menu/lib/shouldShowMenuButton.ts, packages/slate-editor/src/extensions/heading/components/HeadingElement.module.scss, packages/slate-editor/src/extensions/heading/components/HeadingElement.tsx, packages/slate-editor/src/extensions/mentions/useMentions.ts, packages/slate-editor/src/extensions/user-mentions/useUserMentions.ts, packages/slate-editor/src/extensions/variables/useVariables.ts, packages/slate-editor/src/modules/editor/Editor.tsx, packages/slate-editor/src/modules/nodes-hierarchy/fixers/unwrapNode.ts
- renders "Add a title"/"Add a subtitle" for Title and Subtitle headings that have no text
- disables the floating add button for those nodes
- disables variables for those nodes
- no need to disable `#` and `##` shortcuts as those only work on paragraphs
=> [DEV-10911] Render placeholders for Title/Subtitle headings, disable other features

packages/slate-types/src/nodes/HeadingNode.ts
While technically `isTitleHeading` and `isSubtitlteHeading` do assert that the value is `HeadingNode`, the returning type info is not accurate, as the assertion is actually narrower than just a `is HeadingNode`.
- `isTitleHeadingNode`
- `isSubtitleHeadingNode`
=> [DEV-7542] Fix faulty type guards definitions

packages/slate-editor/src/extensions/heading/components/HeadingElement.module.scss, packages/slate-editor/src/extensions/heading/components/HeadingElement.tsx
Change Title/Subtitle placeholders to not produce DOM structure
Otherwise, when navigating the editor content with keyboard arrow keys, it'll do an extra stop after empty title/subtitle nodes (requiring to press Down twice in order to move to the next node).
=> [DEV-10938] Fix - Title/Subtitle placeholders causing kb arrow keys navigation issues

packages/slate-editor/src/components/EditorBlock/EditorBlock.module.scss, packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx
- Inherit border-radius from the EditorBlock root component (DEV-10942)
- Unify outline position (inner vs outer) for all editor block variations -- it's always inner now (DEV-10942)
=> [DEV-10942] Fix - Editor v4 QA 

package.json, packages/slate-commons/package.json, packages/slate-editor/package.json, packages/slate-editor/src/extensions/loader/components/LoaderElement.stories.tsx, packages/slate-editor/src/extensions/placeholders/components/InputPlaceholderElement.stories.tsx, packages/slate-editor/src/extensions/placeholders/components/PlaceholderElement.stories.tsx, packages/slate-editor/src/extensions/placeholders/elements/AttachmentPlaceholderElement.stories.tsx, packages/slate-editor/src/extensions/placeholders/elements/ContactPlaceholderElement.stories.tsx, packages/slate-editor/src/extensions/placeholders/elements/EmbedPlaceholderElement.stories.tsx, packages/slate-editor/src/extensions/placeholders/elements/GalleryPlaceholderElement.stories.tsx, packages/slate-editor/src/extensions/placeholders/elements/ImagePlaceholderElement.stories.tsx, packages/slate-editor/src/extensions/placeholders/elements/MediaPlaceholderElement.stories.tsx, packages/slate-editor/src/extensions/placeholders/elements/SocialPostPlaceholderElement.stories.tsx, packages/slate-editor/src/extensions/placeholders/elements/VideoPlaceholderElement.stories.tsx, packages/slate-editor/src/extensions/placeholders/elements/WebBookmarkPlaceholderElement.stories.tsx, packages/slate-editor/src/modules/editor/Editor.module.scss, packages/slate-editor/src/modules/editor/Editor.tsx, packages/slate-lists/package.json, packages/slate-tables/package.json, packages/slate-types/package.json
- Bump `slate` dependencies to their latest versions
- [Disable unwanted focus ring around the editable area](https://github.com/prezly/slate/commit/a42b182c875e4fe0e53d40cec68d4b3b65246b65) -- fix a regression caused by the upgrade
=> [CARE-1853] Upgrade - Slate

packages/slate-commons/src/commands/index.ts, packages/slate-commons/src/commands/insertNodes.test.tsx, packages/slate-commons/src/commands/insertNodes.ts, packages/slate-commons/src/commands/isAtEmptyBlock.ts, packages/slate-commons/src/hyperscript.ts, packages/slate-editor/src/modules/editor/Editor.test.tsx, packages/slate-editor/src/modules/editor/__snapshots__/Editor.test.tsx.snap, packages/slate-editor/src/modules/editor/__tests__/expected/image-in-h1.json, packages/slate-editor/src/modules/editor/__tests__/expected/marks-in-style.json, packages/slate-editor/src/modules/editor/hyperscript.ts, packages/slate-editor/src/modules/editor/plugins/withDeserializeHtml/withDeserializeHtml.ts
- [Tweak HTML-pasting behaviour](https://github.com/prezly/slate/commit/2c5cafbabb082a42d6462357480f1a70237c2e4b)
To only inherit copied elements block formatting when there are 2+ elements, otherwise we only paste inner contents, preserving the target element block formatting. For example:
- When pasted h1 into a blockquote -- the blockquote will have the h1 contents, but will remain a blockquote.
- When pasted h1 + h2 + paragraph -- the pasted content will replace the blockquote and force the pasted elements block formatting (h1 + h2 + paragraph)
This seems to be better matching what's expected intuitively.
- [Tweak](https://github.com/prezly/slate/commit/a62f77329ecaa56eb38bb77c5e949d449c5336a5) [insertNodes](https://github.com/prezly/slate/commit/a62f77329ecaa56eb38bb77c5e949d449c5336a …
=> [CARE-1853] Fix - Pasting into title subtitle

packages/slate-editor/src/modules/editable/EditableWithExtensions.tsx
See https://stackoverflow.com/questions/12238396/how-to-disable-google-translate-from-html-in-chrome
=> [CARE-2017] Forbid translating editor area

package.json
It is not used anywhere, and `pnpm clean` followed by `pnpm install` works as expected without it, so it shouldn't be a peer dependency of another package AFAIK.
=> Refactor - Remove `canvas` dependency

package.json, packages/slate-editor/src/modules/editor/Editor.test.tsx, packages/slate-editor/src/modules/editor/__tests__/expected/list-normalization-4.json, packages/slate-editor/src/modules/editor/__tests__/input/list-normalization-4.json, packages/slate-editor/src/modules/editor/test-utils.ts, packages/slate-lists/src/lib/index.ts, packages/slate-lists/src/lib/isContainingTextNodes.ts, packages/slate-lists/src/lib/isElementOrEditor.ts, packages/slate-lists/src/normalizations/normalizeListChildren.ts, packages/slate-lists/src/normalizations/normalizeListItemChildren.ts, packages/slate-lists/src/normalizations/normalizeOrphanListItem.ts, packages/slate-lists/src/normalizations/normalizeOrphanListItemText.ts, packages/slate-lists/src/normalizations/normalizeSiblingLists.ts
The problem was in `normalizeOrphanListItem` / `normalizeOrphanListItemText` -- one was applying a fix, and the other one was reverting it back.
=> [CARE-1965] Fix - Infinite list structure normalization loop

packages/slate-editor/src/components/InfoText/InfoText.module.scss, packages/slate-editor/src/components/InfoText/InfoText.tsx, packages/slate-editor/src/extensions/button-block/ButtonBlockExtension.tsx, packages/slate-editor/src/extensions/button-block/components/ButtonBlockElement.tsx, packages/slate-editor/src/extensions/button-block/components/ButtonBlockMenu.module.scss, packages/slate-editor/src/extensions/button-block/components/ButtonBlockMenu.tsx, packages/slate-editor/src/extensions/video/VideoExtension.tsx, packages/slate-editor/src/extensions/video/components/VideoElement.tsx, packages/slate-editor/src/extensions/video/components/VideoMenu.module.scss, packages/slate-editor/src/extensions/video/components/VideoMenu.tsx
- Refactor `InfoText` and its structure content support into shared reusable code
- Use `InfoText` for VideoMenu the same way we use it for ButtonBlock menu (#460)
=> [DEV-11412] Feature - Warn if video size options are not supported by the theme

packages/slate-editor/src/modules/editor/menuOptions.tsx
As I added these keywords before Al created the keywords list, this one didn't have the complete keywords list.
I reviewed the rest for X/Twitter and Instagram, and they were accurate.
=> [DEV-11511] Improve YouTube search keywords

packages/slate-editor/src/extensions/placeholders/PlaceholdersExtension.tsx, packages/slate-editor/src/extensions/placeholders/elements/VideoPlaceholderElement.tsx
The problem with DEV-11546 was that the TikToks URLs are not `video`-type embeds, but a regular rich app iframe.
That's why the Video placeholder did not handle them, not recognizing as a video.
=> [DEV-11546] Add oEmbed-rerouting to Video placeholders too

packages/slate-editor/src/extensions/embed/EmbedExtension.tsx, packages/slate-editor/src/extensions/embed/components/EmbedElement.tsx, packages/slate-editor/src/extensions/story-bookmark/components/StoryBookmarkElement/StoryBookmarkBlock.tsx, packages/slate-editor/src/extensions/web-bookmark/components/WebBookmarkElement.tsx, packages/slate-editor/src/modules/components/BookmarkCard/BookmarkCard.stories.tsx, packages/slate-editor/src/modules/components/BookmarkCard/BookmarkCard.tsx, packages/slate-editor/src/modules/components/BookmarkCard/Container.tsx, packages/slate-editor/src/modules/components/BookmarkCard/index.ts, packages/slate-editor/src/modules/components/index.ts, packages/slate-editor/src/modules/editor/test-utils.ts
The main change here is restructuring the Embed element rendering to fallback to the Bookmark presentation. This happens when both iframe HTML and Screenshot presentations are either disabled or not possible.
The rest of changes are refactoring to simplify the reuse of Bookmark presentation
=> [DEV-11518] Feature - Render Tally embeds as web bookmarks in emails

packages/slate-editor/src/extensions/embed/components/EmbedElement.tsx, packages/slate-editor/src/extensions/embed/components/EmbedMenu.tsx
This reverts #495 
See https://linear.app/prezly/issue/DEV-11536/qa-should-certain-embeds-not-have-resize-controls-if-they-are-always#comment-581fb499 for explanation.
=> [DEV-11536] Revert the disabled size controls for specific embeds

packages/slate-editor/src/extensions/placeholders/components/SearchInputPlaceholderElement.tsx
`invalidateSuggestions` was never passed to the `SearchInputPlaceholder` so the callbacks were never triggered.
=> [CARE-2178] Fix - Provide invalidateSuggestions prop to SearchInputPlaceholder

.github/workflows/build.yml, .github/workflows/dependencies.yml, .github/workflows/storybook.yml, .github/workflows/test.yml, package.json, packages/slate-commons/package.json, packages/slate-editor/package.json, packages/slate-lists/package.json, packages/slate-tables/package.json
I don't think we use older React versions anywhere. Right?
=> [CARE-3589] Drop React v16 and v17 support

lerna.json, package.json, packages/slate-editor/package.json, packages/slate-editor/tsconfig.json
Also updated the `lerna` package with the latest one and replaced oudated `ts-plugin-scss-modules` with `typescript-plugin-css-modules`.
=> [CARE-4306] Update outdated dependencies with security issues

lerna.json, packages/slate-editor/package.json, packages/slate-editor/src/extensions/gallery-bookmark/GalleryBookmarkExtension.tsx, packages/slate-editor/src/extensions/gallery-bookmark/index.ts, packages/slate-editor/src/extensions/gallery-bookmark/lib/createGalleryBookmark.ts, packages/slate-editor/src/extensions/gallery-bookmark/lib/index.ts, packages/slate-editor/src/extensions/placeholders/PlaceholderNode.ts, packages/slate-editor/src/extensions/placeholders/PlaceholdersExtension.tsx, packages/slate-editor/src/extensions/placeholders/PlaceholdersManager.ts, packages/slate-editor/src/extensions/placeholders/elements/GalleryBookmarkPlaceholderElement.tsx, packages/slate-editor/src/extensions/placeholders/elements/index.ts, packages/slate-editor/src/extensions/placeholders/normalization/removeDisabledPlaceholders.ts, packages/slate-editor/src/modules/editor/Editor.tsx, packages/slate-editor/src/modules/editor/getEnabledExtensions.ts, packages/slate-editor/src/modules/editor/menuOptions.tsx, packages/slate-editor/src/modules/editor/test-utils.ts, packages/slate-editor/src/modules/editor/types.ts, packages/slate-editor/src/modules/events/types.ts
This is an extension similar to Story bookmarks that allows the user to select an existing gallery and creates a web bookmark for it with some predefined options (like layout).
=> [DEV-12566] Feature - Implement GalleryBookmark extension

packages/slate-editor/src/extensions/galleries/components/Gallery/GalleryTile.module.scss, packages/slate-editor/src/extensions/galleries/components/Gallery/GalleryTile.tsx
- caption is rendered as a ghost button by default, with pencil and truncation
- when clicked, button changes into an input with the same styling to allow editing
- introduced intermediary state for caption as using the caption prop directly causes the input to rerender on every update, causing a bug that moves the caret to the end of the input
=> [DEV-12552] Feature - Show pencil next to the caption & truncate if needed

packages/slate-editor/package.json, packages/slate-types/package.json
See https://github.com/prezly/javascript-sdk/releases/tag/v21.0.0
=> [CARE-4942] Upgrade @prezly/sdk package

packages/slate-editor/src/extensions/video/components/VideoElement.module.scss, packages/slate-editor/src/extensions/video/components/VideoElement.tsx
Content Renderer Related Changes: https://github.com/prezly/content-renderer-react-js/pull/85
| Before | After |
|--------|--------|
| ![image](https://github.com/prezly/slate/assets/67554982/7a2c18ed-45b3-4c33-9986-6ddf6c6c8436) | ![Screenshot 2024-06-25 121822](https://github.com/prezly/slate/assets/67554982/7e82282c-89fa-4b5a-9b6f-f83c079b1094) |
=> [CARE-5260] Fix - Ensure vertical videos are centered

packages/slate-editor/src/extensions/paragraphs/ParagraphsExtension.tsx, packages/slate-editor/src/extensions/paragraphs/components/ParagraphElement.tsx, packages/slate-editor/src/extensions/paragraphs/test-utils.ts, packages/slate-editor/src/modules/editor/Editor.tsx, packages/slate-editor/src/modules/editor/getEnabledExtensions.ts, packages/slate-editor/src/modules/editor/test-utils.ts
Previously, if default alignment was applied to the paragraph (in our case `left`), it would not render the `text-align: left` style property.
This caused a bug in the tables, more specifically table header cell, which by default aligns the text to the center.
The solution is to explicitly render the `text-align` style property even if default alignment is used.
=> [CARE-5345] Fix - Always set the `text-align` property on paragraph

packages/slate-editor/src/extensions/floating-add-menu/components/Dropdown.module.scss
=> [CARE-4614] Fix - Use proper fill for gallery bookmarks

packages/slate-editor/src/components/EditorBlock/EditorBlock.module.scss, packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx, packages/slate-editor/src/extensions/tables/components/elements/TableElement.tsx
Previously the table element was using `overflow: hidden`, now it will use `overflow: auto` showing a scrollbar if needed.
=> [CARE-5666] Fix - Use overflow: auto in tables

packages/slate-editor/src/components/NewParagraphDelimiter/NewParagraphDelimiter.tsx
This took me a while to figure out but the problem was that new paragraph delimiter has `contenteditable="false"` so Slate was executing [this compatibility code](https://github.com/ianstormtaylor/slate/blob/5838e36229750863bfe3b499632dd3d92594bbe5/packages/slate-react/src/plugin/react-editor.ts#L982-L984) in Chrome, treating the element like a non-void, but it is in reality a void element.
=> Mark new paragraph delimiter as void

packages/slate-editor/src/extensions/web-bookmark/components/WebBookmarkMenu.tsx
If it's not possible to change to an embed, we hide the option instead of disabling it.
=> [CARE-4612] Fix - Hide embed option if it's not available

packages/slate-editor/src/components/Button/Button.module.scss, packages/slate-editor/src/components/Button/Button.stories.tsx, packages/slate-editor/src/components/Button/Button.tsx, packages/slate-editor/src/components/Toolbox/Caption.tsx, packages/slate-editor/src/components/Toolbox/Header.tsx, packages/slate-editor/src/components/Toolbox/Toolbox.module.scss, packages/slate-editor/src/components/Toolbox/Toolbox.stories.tsx, packages/slate-editor/src/extensions/embed/components/EmbedMenu.tsx, packages/slate-editor/src/extensions/file-attachment/components/FileAttachmentMenu.tsx, packages/slate-editor/src/extensions/galleries/components/GalleryMenu.tsx, packages/slate-editor/src/extensions/image/components/ImageMenu.tsx, packages/slate-editor/src/extensions/inline-contacts/components/InlineContactMenu.tsx, packages/slate-editor/src/extensions/press-contacts/components/PressContactMenu.tsx, packages/slate-editor/src/extensions/story-bookmark/components/StoryBookmarkMenu.tsx, packages/slate-editor/src/extensions/tables/components/TableMenu.tsx, packages/slate-editor/src/extensions/video/components/VideoMenu.tsx, packages/slate-editor/src/extensions/web-bookmark/components/WebBookmarkMenu.tsx, packages/slate-editor/src/modules/rich-formatting-menu/LinkMenu.tsx
- toolbox header now uses full opacity
- default (medium) button size changed to 14 px
- introduced "small" and "tiny" sizes
- removed `noPadding` variant
- "Remove X" changed to simply "Remove"
- various edit/view links shuffled to the bottom, above the "Remove" button
=> [CARE-4611] Feature - Tweak various element menus

packages/slate-editor/src/extensions/mentions/components/MentionsDropdown.module.scss, packages/slate-editor/src/extensions/mentions/components/MentionsDropdown.tsx, packages/slate-editor/src/extensions/mentions/lib/getWordAfterTrigger.ts
=> [CARE-2935] Fix - Make sure the trigger character is only detected in the same node

packages/slate-editor/src/extensions/coverage/CoverageExtension.tsx, packages/slate-editor/src/extensions/coverage/components/CoverageElement.tsx, packages/slate-editor/src/extensions/coverage/components/CoverageMenu.tsx, packages/slate-editor/src/extensions/coverage/types.ts, packages/slate-editor/src/modules/editor/test-utils.ts
I had to move the "Open in new tab" option to a separate section since it was previously part of the "Layout" section, which is now optional.
=> [CARE-5752] Feature - Make layout options optional in coverage settings

packages/slate-editor/src/components/EditorBlock/getMenuPopperModifiers.ts, packages/slate-editor/src/components/EditorBlock/index.ts, packages/slate-editor/src/components/Menu/Dropdown.module.scss, packages/slate-editor/src/components/Menu/Dropdown.tsx, packages/slate-editor/src/components/Toolbox/Caption.tsx, packages/slate-editor/src/extensions/mentions/lib/insertMention.test.tsx, packages/slate-editor/src/extensions/mentions/lib/insertMention.ts, packages/slate-editor/src/extensions/mentions/useMentions.ts, packages/slate-editor/src/extensions/variables/VariableElement.module.scss, packages/slate-editor/src/extensions/variables/VariableElement.tsx, packages/slate-editor/src/extensions/variables/VariableMenu.module.scss, packages/slate-editor/src/extensions/variables/VariableMenu.tsx, packages/slate-editor/src/extensions/variables/VariablesExtension.tsx, packages/slate-editor/src/extensions/variables/lib/createVariableNode.ts, packages/slate-editor/src/extensions/variables/normalization/removeUnknownVariableNodeAttributes.ts, packages/slate-editor/src/extensions/variables/transforms/index.ts, packages/slate-editor/src/extensions/variables/transforms/removeVariable.ts, packages/slate-editor/src/extensions/variables/transforms/updateVariable.ts, packages/slate-editor/src/extensions/variables/types.ts, packages/slate-editor/src/extensions/variables/useVariables.ts, packages/slate-editor/src/index.ts, packages/slate-editor/src/modules/popper-options-context/types.ts, packages/slate-types/src/nodes/VariableNode.ts
- variables no longer show as `%something%` but instead use the label for better clarity
- variables now have a menu when selected
- variables that have `withFallback: true` can have a text fallback set for them
I still have to run this with the UX people so the UI might change.
Default:
With fallback defined:
Choosing different options:
=> [DEV-13254] Implement settings menu for variables with optional fallback

packages/slate-editor/src/extensions/variables/VariableMenu.tsx
Based on the feedback in https://github.com/prezly/slate/pull/562#discussion_r1709335012.
=> Remove fallback when changing the type instead of using an effect

packages/slate-editor/src/extensions/inline-links/InlineLinksExtension.tsx, packages/slate-editor/src/extensions/inline-links/components/LinkElement.tsx, packages/slate-editor/src/extensions/inline-links/index.ts, packages/slate-editor/src/extensions/inline-links/types.ts, packages/slate-editor/src/lib/humanFriendlyEmailUrl.ts, packages/slate-editor/src/lib/index.ts, packages/slate-editor/src/lib/urls.ts, packages/slate-editor/src/modules/components/LinkWithTooltip/LinkWithTooltip.tsx, packages/slate-editor/src/modules/editor/getEnabledExtensions.ts, packages/slate-editor/src/modules/editor/types.ts, packages/slate-editor/src/modules/rich-formatting-menu/LinkMenu.module.scss, packages/slate-editor/src/modules/rich-formatting-menu/LinkMenu.tsx, packages/slate-editor/src/modules/rich-formatting-menu/RichFormattingMenu.tsx, packages/slate-editor/src/modules/rich-formatting-menu/types.ts
Allow choosing what kind of link the user is trying to add (web is the default):
If email is choosed, the email address will be normalized upon saving into `mailto:your@email.com`.
When editing an email link, it is "humanized" before being presented in the input so the `mailto:` gets stripped.
Also allow selecting predefined values (variables) as link hrefs, used for the new unsubscribe URL and also for the already implemented story and short story URLs:
The link tooltip reflects this and shows the human variable name (previously it would show a clickable `%release.url%` leading nowhere):
=> [CARE-5911] Introduce "type" dropdown into the link menu, allow predefined values as links

packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx
To allow styling these blocks with an external stylesheet
=> [CARE-5939] Expose EditorBlock `align` mode as an HTML attr

packages/slate-editor/src/extensions/variables/VariableMenu.tsx
=> [CARE-5943] Hide settings menu if there's only one option without a fallback support

packages/slate-editor/src/components/SearchInput/Panel.module.scss, packages/slate-editor/src/components/SearchInput/Panel.tsx, packages/slate-editor/src/components/SearchInput/SearchInput.stories.tsx, packages/slate-editor/src/components/SearchInput/SearchInput.tsx, packages/slate-editor/src/components/SearchInput/Suggestions.module.scss, packages/slate-editor/src/components/SearchInput/Suggestions.tsx, packages/slate-editor/src/extensions/placeholders/components/InputPlaceholder.tsx, packages/slate-editor/src/extensions/placeholders/elements/ContactPlaceholderElement.tsx, packages/slate-editor/src/extensions/placeholders/elements/CoveragePlaceholderElement.module.scss, packages/slate-editor/src/extensions/placeholders/elements/CoveragePlaceholderElement.tsx, packages/slate-editor/src/extensions/placeholders/elements/GalleryBookmarkPlaceholderElement.tsx, packages/slate-editor/src/extensions/placeholders/elements/InlineContactPlaceholderElement/InlineContactPlaceholderElement.tsx, packages/slate-editor/src/extensions/placeholders/elements/StoryBookmarkPlaceholderElement.tsx, packages/slate-editor/src/extensions/placeholders/elements/StoryEmbedPlaceholderElement.tsx, packages/slate-editor/src/icons/Upload.svg, packages/slate-editor/src/icons/index.ts
- updated title and description of the placeholder
- input is now properly autofocused
- added ability to upload a file via Uploadcare
=> [DEV-13410] Fix - Coverage placeholder fixes

packages/slate-editor/src/components/SearchInput/Suggestions.tsx
I've noticed some problems in the app with the usage of Popper, so I've brought back the minHeight and maxHeight calculation, so Popper doesn't have to flip the entire dropdown unless the available space is less than minHeight.
This makes the dropdown still usable while opened near the bottom of the screen.
There was also a bug with the position of the dropdown when addon is present - this was due to usage of `bottom` placement which anchors to the center of the element (the search input). I've changed it to anchor to `bottom-end`, so it's always aligned.
Another thing that has been fixed is the active element is now properly visible when the dropdown is displayed (previously the active item was sometimes hidden, since the dropdown was scrolled down a bit).
=> [DEV-13410] Fix - Coverage placeholder search input

packages/slate-editor/src/extensions/placeholders/PlaceholdersExtension.tsx, packages/slate-editor/src/extensions/placeholders/components/PlaceholderElement.tsx, packages/slate-editor/src/extensions/placeholders/elements/ContactPlaceholderElement.stories.tsx, packages/slate-editor/src/extensions/placeholders/elements/ContactPlaceholderElement.tsx, packages/slate-editor/src/extensions/placeholders/elements/CoveragePlaceholderElement.module.scss, packages/slate-editor/src/extensions/placeholders/elements/CoveragePlaceholderElement.tsx, packages/slate-editor/src/extensions/placeholders/elements/GalleryBookmarkPlaceholderElement.tsx, packages/slate-editor/src/extensions/placeholders/elements/InlineContactPlaceholderElement/InlineContactPlaceholderElement.tsx, packages/slate-editor/src/extensions/placeholders/elements/StoryBookmarkPlaceholderElement.stories.tsx, packages/slate-editor/src/extensions/placeholders/elements/StoryBookmarkPlaceholderElement.tsx, packages/slate-editor/src/extensions/placeholders/elements/StoryEmbedPlaceholderElement.stories.tsx, packages/slate-editor/src/extensions/placeholders/elements/StoryEmbedPlaceholderElement.tsx, packages/slate-editor/src/modules/editor/test-utils.ts, packages/slate-editor/src/modules/events/types.ts
The main idea behind this refactoring is to simplify the rendering of placeholders, allowing full control over the contents of the placeholders as soon as they're clicked and to also improve the developer experience when adding or modifying the existing UI. Since a lot of the placeholder code will now be part of the consumer codebase, we don't have to release new versions of the editor when doing copy changes for example.
I chose the `GalleryBookmarkPlaceholderElement` as a proof of concept since it also contains the site switcher. The plan is (if we agree to it) to rework the remaining "search input" placeholders and then eventually rework the regular "input" placeholders as well.
The interface has been simplified into sort of a "headless" approach, so now the consumer only needs to …
=> [DEV-13852] Refactoring - Allow custom rendering of placeholders

packages/slate-editor/src/components/Portals/BasePortalV2.tsx, packages/slate-editor/src/modules/rich-formatting-menu/RichFormattingMenu.tsx
I've also fixed a bug with the arrow using the "desired" placement value instead of the actual value.
=> [DEV-18770] Fix - Allow LinkMenu to flip so it's not cut off if there's not enough space

packages/slate-editor/src/extensions/snippet/lib/useFloatingSnippetInput.ts, packages/slate-editor/src/modules/components/FloatingSnippetInput/FloatingSnippetInput.tsx, packages/slate-editor/src/modules/editor/Editor.tsx
- added `useFunction` to not create new function references on every render
- memoized the `FloatingSnippetInput` component to not re-render if the props haven't changed
=> [DEV-15524] Fix - Make sure FloatingSnippetInput is not re-rendering if not needed
